version: "3.7"

services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "8080:8080"
    volumes:
      - ./config.php:/var/www/html/config.php

  # mysql:
  #   image: mariadb
  #   ports:
  #     - 14306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - MYSQL_DATABASE=trss
