name: Publish Docker Hub
on:
  push:
      branches:
          - production
jobs:

  build_publish_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Build and push
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: iben12/trss
        tags: latest, ${{ env.GITHUB_SHA_SHORT }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.2"
    - name: Checkout GitOps repo
      run: git clone https://${GITOPS_TOKEN}@github.com/iben12/k8city-apps.git gitops
      env:
        GITOPS_TOKEN: ${{secrets.GITOPS_TOKEN}}
    - name: Run Kustomize
      working-directory: ./gitops/own-projects/trss
      run: kustomize edit set image iben12/trss:${{ env.GITHUB_SHA_SHORT }}
    - name: Configure Git
      working-directory: ./gitops
      run: |
        git config --global user.email "deployer@skizoidglam.net"
        git config --global user.name "GitOps deployer"
    - name: Stage changes
      working-directory: ./gitops
      run: git add .
    - name: Commit changes
      working-directory: ./gitops
      run: git commit -m "Release trss-${{ env.GITHUB_SHA_SHORT }}"
    - name: Push
      working-directory: ./gitops
      run: git push origin master
