name: Publish Docker Hub
on:
  push:
      branches:
          - production
jobs:

  build_publish_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      env:
        DOCKER_BUILDKIT: 1
      run: docker build -t iben12/trss --target final .
    - name: Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY_URL: "docker.io"
      run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
    - name: Push
      run: docker push iben12/trss:latest
